name: Build and Release

env:
  CI: true
on:
  push:
    branches:
      - release

permissions:
  contents: write
  packages: write
jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: "https://npm.pkg.github.com"
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.1.9
          run_install: false
      - name: install
        run: pnpm i 
      - name: build
        run: pnpm build
      # if unpublished, publish with current version
      - name: publish
        working-directory: ./packages/node-cli
        run: |
          npx can-npm-publish --verbose && npm publish || echo "Does not publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
