name: Build and Release

env:
  CI: true
on:
  push:
    branches:
      - release

permissions:
  contents: write
  packages: write
jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: "https://npm.pkg.github.com"
      - name: install
        run: npm install
      - name: build
        run: npm run build
      # if unpublished, publish with current version
      - name: publish
        run: |
          npx can-npm-publish --verbose && npm publish || echo "Does not publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
